# /.tmuxinator.yml
name: zuse-neat-rust
root: /development/rust_proj/zuse-neat-rust

startup_window: neat

windows:
  - neat:
      layout: 3ccd,274x63,0,0{90x63,0,0,47,90x63,91,0,49,92x63,182,0[92x22,182,0,50,92x21,182,23,51,92x18,182,45,52]}
      panes:
        -
        - note:
            - cargo check
            - git status -sb
            - 
        - 
        - 
        - 
  - tests:
      layout: 3ccd,274x63,0,0{90x63,0,0,47,90x63,91,0,49,92x63,182,0[92x22,182,0,50,92x21,182,23,51,92x18,182,45,52]}
      panes:
        - 
        - 
        - 
        - 
        - 
